name: "Pari Patel - Portfolio"
description: "Lightweight theme"
google: "UA-151543398-1"
url: 'https://pkp68.github.io'
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

